-- HELIOS-99030 v3 end-to-end DSARC gate test (Replit path)
-- Pure DDL: the classifier must flag SyncHasDdl=true so the gate fires on the
-- release-dsarc-replit-test prod target and creates a DSARC YouTrack ticket.
CREATE TABLE omnisync.e2e_ddl_test_v3 (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note        TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
